name: Setup CI

on:
  push:
    branches: [ test, deploy ]

jobs:
  build:

    runs-on:
      - self-hosted
      - ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version-file: .nvmrc
        registry-url: https://npm.pkg.github.com
        scope: '@mintlayer'
    - name: Install dependencies
      run: yarn --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Debugging
      run: |
        if [ ${{ github.ref }} == 'refs/heads/test' ]; then
          yarn coverage
        elif [ ${{ github.ref }} == 'refs/heads/deploy' ]; then
          echo "debugging => deploy"
        fi
